version = 0.1
[default.pipeline_bootstrap.parameters]
pipeline_user = "arn:aws:iam::908198849120:user/aws-sam-cli-managed-dev-pipeline-resou-PipelineUser-oNMdAeB8XHv4"
permissions_provider = "AWS IAM"

[dev.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::908198849120:role/aws-sam-cli-managed-dev-pipel-PipelineExecutionRole-LuwDYRnd0ytU"
cloudformation_execution_role = "arn:aws:iam::908198849120:role/aws-sam-cli-managed-dev-p-CloudFormationExecutionRo-3fCCdvQJDLy0"
artifacts_bucket = "aws-sam-cli-managed-dev-pipeline-r-artifactsbucket-cnfqdntgmjcz"
image_repository = ""
region = "ap-south-1"

[prod.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::908198849120:role/aws-sam-cli-managed-prod-pipe-PipelineExecutionRole-fzTSsi2L6vp1"
cloudformation_execution_role = "arn:aws:iam::908198849120:role/aws-sam-cli-managed-prod--CloudFormationExecutionRo-g1TtBnp72ZjD"
artifacts_bucket = "aws-sam-cli-managed-prod-pipeline--artifactsbucket-ddpck2wonat3"
image_repository = ""
region = "ap-south-1"
